TestProject.Webs/Controllers/CatalogController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TestProject.BLL.DTO;
using TestProject.BLL.Infrastructure;
using TestProject.BLL.Interfaces;
using TestProject.DAL.Entities;
using TestProject.Webs.Models;

namespace TestProject.Webs.Controllers
{
    [Authorize]
    public class CatalogController : Controller
    {
        private readonly ILogger<CatalogController> _logger;

        private readonly ICatalogService _catalogService;
        public CatalogController(ILogger<CatalogController> logger,ICatalogService catalogService)
        {
            _logger = logger;
            _catalogService = catalogService;
        }
        
        public IActionResult Products()
        {
            IEnumerable<ProductDTO> productDTOs = _catalogService.GetProducts();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<ProductDTO, ProductViewModel>()).CreateMapper();
            ViewBag.Products = mapper.Map<IEnumerable<ProductDTO>, List<ProductViewModel>>(productDTOs);
            ViewBag.User = _catalogService.GetUserRole(User.Identity.Name);
            return View();
        }
        [Authorize(Roles = "Administrator, AdvanceUser")]
        public IActionResult AddProduct()
        {
            IEnumerable<CategoryDTO> categoryDTOs = _catalogService.GetCategories();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CategoryDTO, CategoryViewModel>()).CreateMapper();
            ViewBag.Categories = mapper.Map<IEnumerable<CategoryDTO>, List<CategoryViewModel>>(categoryDTOs);
            return View();
        }

        [Authorize(Roles = "Administrator, AdvanceUser")]
        [HttpPost]
        public IActionResult AddNewProduct(string name,int categoryId,string discription, String price, string generalNote,string specialNote )
        {
            try
            {
                var category = _catalogService.GetCategory(categoryId);
      
                var productDTO = new ProductDTO { Name = name, Category = category, Discription=discription, Price= float.Parse(price), GeneralNote=generalNote, SpecialNote=specialNote };
                _catalogService.AddProduct(productDTO);
                return Redirect("/Catalog/Products");
            }
            catch (ValidationException ex)
            {
                return BadRequest(ex.Message);
            }
            catch(FormatException ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [Authorize(Roles = "Administrator, AdvanceUser")]
        public IActionResult UpdateProduct(int id)
        {
            IEnumerable<CategoryDTO> categoryDTOs = _catalogService.GetCategories();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CategoryDTO, CategoryViewModel>())
            .CreateMapper();
            ViewBag.Categories = mapper.Map<IEnumerable<CategoryDTO>, List<CategoryViewModel>>(categoryDTOs);


            ProductDTO productDTO = _catalogService.GetProduct(id);
            mapper = new MapperConfiguration(cfg => cfg.CreateMap<ProductDTO, ProductViewModel>()
            .ForMember(m=>m.CategoryId, opt => opt.MapFrom(src =>src.Category.Id))).CreateMapper();
            ViewBag.Product = mapper.Map<ProductDTO, ProductViewModel>(productDTO);
            return View();
        }

        [Authorize(Roles = "Administrator, AdvanceUser")]
        [HttpPost]
        public IActionResult UpdateNewProduct(int id,string name, int categoryId, string discription, String price, string generalNote, string specialNote)
        {
            try
            {
                var category = _catalogService.GetCategory(categoryId);
                var productDTO = new ProductDTO {Id=id, Name = name, Category = category, Discription = discription, Price = float.Parse(price), GeneralNote = generalNote, SpecialNote = specialNote };
                _catalogService.UpdateProduct(productDTO);
                return Redirect("/Catalog/Products");
            }
            catch (ValidationException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (FormatException ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [Authorize(Roles = "Administrator, AdvanceUser")]
        public IActionResult DeleteProduct(int id)
        {

            ProductDTO productDTO = _catalogService.GetProduct(id);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<ProductDTO, ProductViewModel>()
            .ForMember(m => m.CategoryId, opt => opt.MapFrom(src => src.Category.Id))
            .ForMember(m => m.CategoryName, opt => opt.MapFrom(src => src.Category.Name))).CreateMapper();
            ViewBag.Product = mapper.Map<ProductDTO, ProductViewModel>(productDTO);
            return View();
        }

        [Authorize(Roles = "Administrator, AdvanceUser")]
        [HttpPost]
        public IActionResult DeleteProductPost(int id)
        {
            try
            {
                _catalogService.DeleteProduct(id);
                return Redirect("/Catalog/Products");
            }
            catch (ValidationException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (FormatException ex)
            {
                return BadRequest(ex.Message);
            }
        }


        public IActionResult Categories()
        {
            IEnumerable<CategoryDTO> categoryDTOs = _catalogService.GetCategories();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CategoryDTO, CategoryViewModel>()).CreateMapper();
            ViewBag.Categories = mapper.Map<IEnumerable<CategoryDTO>, List<CategoryViewModel>>(categoryDTOs);
            ViewBag.User = _catalogService.GetUserRole(User.Identity.Name);

            return View();
        }
        [Authorize(Roles ="Administrator")]
        public IActionResult AddCategory()
        {
            return View();
        }
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public IActionResult AddNewCategory(string name)
        {
            try
            {
                var categoryDTO = new CategoryDTO { Name = name };
                _catalogService.AddCategory(categoryDTO);
                return Redirect("/Catalog/Categories");
            }
            catch (ValidationException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (FormatException ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult UpdateCategory(int id)
        {
            CategoryDTO categoryDTO = _catalogService.GetCategory(id);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CategoryDTO, CategoryViewModel>()).CreateMapper();
            ViewBag.Category = mapper.Map<CategoryDTO, CategoryViewModel>(categoryDTO);
            return View();
        }
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public IActionResult UpdateNewCategory(int id, string name)
        {
            try
            {
                var categoryDTO = new CategoryDTO
                {
                    Id = id,
                    Name = name
                };
                _catalogService.UpdateCategory(categoryDTO);
                return Redirect("/Catalog/Categories");
            }
            catch (ValidationException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (FormatException ex)
            {
                return BadRequest(ex.Message);
            }
        }
        [Authorize(Roles = "Administrator")]
        public IActionResult DeleteCategory(int id)
        {

            CategoryDTO categoryDTO = _catalogService.GetCategory(id);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CategoryDTO, CategoryViewModel>()).CreateMapper();
            ViewBag.Category = mapper.Map<CategoryDTO, CategoryViewModel>(categoryDTO);
            return View();
        }
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public IActionResult DeleteCategoryPost(int id)
        {
            try
            {
                _catalogService.DeleteCategory(id);
                return Redirect("/Catalog/Categories");
            }
            catch (ValidationException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (FormatException ex)
            {
                return BadRequest(ex.Message);
            }
        }

        public IActionResult SpecificCategory(int id)
        {
            IEnumerable<ProductDTO> productDTOs = _catalogService.GetSpecificProducts(id);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<ProductDTO, ProductViewModel>()).CreateMapper();
            ViewBag.Products = mapper.Map<IEnumerable<ProductDTO>, List<ProductViewModel>>(productDTOs);
            ViewBag.Category = _catalogService.GetCategory(id).Name;
            ViewBag.User = _catalogService.GetUserRole(User.Identity.Name);
            return View();
        }

        public IActionResult SearchProducts(string name = "")
        {
            IEnumerable<ProductDTO> productDTOs = _catalogService.SearchProducts(name);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<ProductDTO, ProductViewModel>()).CreateMapper();
            ViewBag.Products = mapper.Map<IEnumerable<ProductDTO>, List<ProductViewModel>>(productDTOs);
            ViewBag.Name = name;
            ViewBag.User = _catalogService.GetUserRole(User.Identity.Name);
            return View();
        }

TestProject.Webs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestProject.Webs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Catalog" asp-action="Products">TestProject.Webs</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Products">Продукты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Categories">Категории</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="SearchProducts">Поиск</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="FilterProducts">Фильтр</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Logout">Выход</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TestProject.Webs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>